Update error message for operations on default identity - OSD-5379
openshift/managed-cluster-validating-webhooks pull request #116
Opened 2020-10-23 18:19 UTC by csheremeta

2020-10-24 03:55 UTC, lisa requested changes
/hold

2020-10-24 03:55 UTC, lisa commented on pkg/webhooks/identity/identity.go
> +		ret = admissionctl.Denied("Prevented from modifying Red Hat's managed Identity. You may create/modify any Identity objects, except for 'OpenShift_SRE'.")
Should reference the constant in this package.

2020-10-26 14:29 UTC, lisa requested changes

2020-10-26 14:29 UTC, lisa commented on pkg/webhooks/identity/identity.go
> +		ret = admissionctl.Denied("Prevented from modifying Red Hat's managed Identity. You may create/modify any Identity objects, except for 'OpenShift_SRE'.")
```suggestion
		ret = admissionctl.Denied(fmt.Sprintf("Prevented from modifying Red Hat's managed Identity. You may create/modify any Identity objects, except for %s.", DefaultIdentityProvider))
```

2020-10-26 14:29 UTC, lisa commented on pkg/webhooks/identity/identity.go
> +		ret = admissionctl.Denied("Prevented from modifying Red Hat's managed Identity. You may create/modify any Identity objects, except for 'OpenShift_SRE'.")
Suggestion to implement for my [previous comment](https://github.com/openshift/managed-cluster-validating-webhooks/pull/116/files#r511300954).

2020-11-03 16:06 UTC, csheremeta commented
@lisa suggested changes have been committed, let me know if you think this looks good to go

2020-11-13 15:05 UTC, lisa commented
/lgtm
/approve

2020-11-13 15:18 UTC, lisa commented
/unhold

whoops, forgot one important step

2020-11-13 15:26 UTC, merged